import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dirSize } from "@/shared/fileHelpers";
import ProgressBar from "@/components/ProgressBar/ProgressBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getPercents (a : number, b : number) {
  return a / b * 100
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const size = await dirSize()
  const maxSize = 1024*10

  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="box-border bg-gray-100 p-2 h-[100vh]">
      <div className="grid gap-2 grid-cols-[300px_auto] h-[calc(100vh-1rem)]">
        <aside className="grid grid-subgrid grid-rows-[70px_auto] gap-2">
          <div className="bg-white flex justify-center items-center">
            <div className="text-xl">Мой диск</div>
          </div>

          <div className="bg-white p-3">
            <div className="text-lg">Использовано</div>
            <ProgressBar progress={getPercents(size, maxSize)} />
            <div className="text-sm text-gray-500 mt-1">
              {size}B из {maxSize}B
            </div>
          </div>
        </aside>
        <main className="grid grid-subgrid grid-rows-[70px_auto] gap-2">
          <div className="bg-white flex items-center p-3">
            {/* <Input
              before={<IconSearch width={16} />}
              placeholder="Search"
              width={"300px"}
              onInput={(e: any) => setSearch(e.target.value)}
              onEnterPress={() => searchValue(search)}
            /> */}
          </div>

          <div className="bg-white p-3">
            {children}
          </div>
        </main>
      </div>
    </div>
      </body>
    </html>
  );
}
